In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
c=np.array([1,2,3,4,5,6]).reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
e=np.array([1,2,3,4,5,6])
print(e.sum())
print(e.min())
print(e.max())
print(e.mean())

21
1
6
3.5


In [5]:
np.linspace(0,6,10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [6]:
np.random.rand(4)

array([0.30027552, 0.51815178, 0.37582979, 0.27715643])

In [7]:
np.random.randint(2,8)

4

In [8]:
np.arange(34)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])